### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by ldarren** [ldarren/pico-client#38]
```
./build.sh pdl_agent dev
js/Frame:50
return Module.View.extend({
                  ^

TypeError: Cannot read property 'extend' of undefined
    at Object.eval (js/Frame:50:19)
    at compile (/opt/pico/common/pico.js:85:10)
    at js (/opt/pico/common/pico.js:138:10)
    at /opt/pico/common/pico.js:58:33
    at /opt/pico/common/pico.js:205:13
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
done
```

i have rebuilt common and lean

**Comment by ldarren** [comment]
fixed by making file operation in build process syncronous
